# frozen_string_literal: true

source "https://rubygems.org"
#gemspec

#gem "jekyll", ENV["JEKYLL_VERSION"] if ENV["JEKYLL_VERSION"]
gem "kramdown-parser-gfm" if ENV["JEKYLL_VERSION"] == "~> 3.9"

gem "base64"
gem "csv"
gem "logger"

gem "jekyll"

# Built-in
# gem 'jekyll-sass-converter'

# Feed had been built in; From 4.4??
group :jekyll_plugins do
  # gem 'jekyll-archives'
  gem 'jekyll-babel'

  # jekyll-html-pipeline

  # kramdown v2 ships without the gfm parser by default. If you're using
  # kramdown v1, comment out this line.
  gem 'kramdown-parser-gfm'

  # jekyll-paginate
  # gem 'jekyll-relative-links'
  gem 'jekyll-redirect-from'
  #  spec.add_runtime_dependency "jekyll-feed", "~> 0.9"
  #  spec.add_runtime_dependency "jekyll-seo-tag", "~> 2.1"
# Feed had been built in
  # gem 'jekyll-feed'                 # automatically generate an Atom feed at /feed.xml
# Feed had been built in

  gem 'jekyll-timeago'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jemoji'
  # gem "just-the-docs"
  gem 'jekyll-gist'
end

