# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title:

# Below the site title
tagline: Tales

# Site logo
logo:

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/


# Social links in the site footer
github_username: "username"
medium_username: "@username"
#codepen_username: "username"
#linkedin_username: "username"

#permalink: pretty
#permalink: :title/
permalink: :collection/:title/
#permalink: /:collection/:title/
markdown: kramdown
kramdown:
    auto_ids: true

collections:
  note:
    # Default is "/:path/"
    #for collections, :collection is part of path
    #permalink: /:collection/:title/
    layout: post
    output: true
  posts:
    #permalink: /:collection/:path/
    #permalink: /:collection/:title/
    layout: post
    #output: true    # always true

#defaults            : []
defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      # so as not to add layout to each file
      layout: post
      # types available are pages, posts, or any collection, in plural form
      type: posts
      # The 'post' type has become 'posts'.
      category: "journal"
      image: "/img/jekyll-og.png"
      #permalink: /:title/
