# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# modern flat style and beautiful
# night/dark mode.
#
# NOTE:
#      some of the settings in this file get overwritten in later config
#      files like _prod.yml, _dev.yml, and _defaults.yml

# the docs version that is shown by default when clicking on docs links on the site
default_linked_docs_version: latest

# the language that serves as the source for the translations
src_language: en

language: en

# Build settings
#source:      www
#destination: build-dev

# don't erase these files in the output directory
keep_files: [".git", ".svn", "wiki-images", "images", "downloads"]

# Site settings
email: aaron@ashang.org
author: aaron

heading: H
subheading: "S"
banner: "B"
title:
title:          Tale <ruby>sim<rt>ops</rt></ruby> notes

# Below the site title
tagline: Tales

# Site logo
logo:

# Assets
sass:
  sass_dir: _sass
  #style:        compressed
  #style:
  # possible values: nested expanded compact compressed
  # possible values: expanded compressed --DART styles now
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  # sourcemap: true # Produces an error

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
#- text: About
#  url: /about/
#- text: Archive
#  url: /archive/

# Social links in the site footer
github_username: "username"
medium_username: "@username"
#codepen_username: "username"
#linkedin_username: "username"

#permalink_defaults:
#[permalinks]
#	page: "/:title/"
#	about: "/:filename/"
permalink: /:title/
#permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
#ilwt/_config.yml:pretty_urls:
#hexo-new/_config.yml:pretty_urls:
#content/_config.yml:url-pretty: "MyWebsite.com"

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
# copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl: "" # the subpath of your site, e.g. /weblog

url: "" # the base hostname & protocol for your site, e.g. https://example.com
#url:            "https://chesterhow.github.io"
favicon: "" # the favicon for your site

# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %d, %Y"

# If you want more debug log, you can set true
# debug: false

# If you don't want transparent header, you can set false
# header_transparent: true
# header_transparent: true

# If you want to change the content width, you can set to another value
# content_width: "920px"
# content_width: "920px"

# Google analytics
# google_analytics: [Tracking ID]

# If you want to generate website sitemap, you can set true
# sitemap: false

# If you want to change site language, you can set lang option
# lang: "en"  # default lang is en

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
# translate_langs:
#   - lang: en
#     img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
#     text: English
#
#   - lang: fr
#     img: https://cdn.countryflags.com/thumbs/france/flag-400.png
#     text: French
#
#   - lang: ja
#     img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
#     text: Japanese
#
#   - lang: ko
#     img: https://cdn.countryflags.com/thumbs/south-korea/flag-400.png
#     text: Korean

# You can choose a theme color
# Default theme colors as below:
# coolblack: #090a0b
# spacegrey: #353535
# snowwhite: #ffffff
#
# theme_color: snowwhite
#
# Custom color as below:
# theme_color: "#882250"

# You can choose a brand color
# Default brand colors as below:
# orangered: #ff5100
# greatgold: #f2cb05
# greenblue: #389092
#
# brand_color: orangered
#
# Custom color as below:
# brand_color: "#1a8e42"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
# night_mode: "auto"

# Code badge setting
# You can enable or disable the code badge and so on
# code_badge:
#   enabled: "true"
#   color: "#fff"
#   background_color: "#ff4e00"
#   text_transform: "uppercase"  # ("uppercase", "lowercase", "capitalize")

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - index.html
#   - archive.html
#   - about.md

# Banner default settings
# These banner settings are for global banner default, but you can also
# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minimum height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)
#  loop: true
#  volume: 0.8
#  start_at: 8.5
#  opacity: 0.618
#  background: "#000"
#  height: "100vh"
#  min_height: "38vh"
#  heading_style: "font-size: 4.25em; font-weight: bold; text-decoration: underline"
#  subheading_style: "color: gold"

# Gitment comments
# gitment:
#   username: "Your GitHub username"
#   repo: "The repo to store comments"
#   client_id: "Your client ID"
#   client_secret: "Your client secret"
#   redirect_uri: "Your redirect url"   # If you use a custom domain name

# Utterances comments
# See https://utteranc.es/
# set follow_site_theme true to make utterances' theme follow the site's

# utterances:
#   repo: "owner/repo"
#   issue_term: "title"
#   label: "utterances comment"
#   theme: "github-light"
#   follow_site_theme: true

# Build settings
#markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: plaintext
    span:
      disable: true
  entity_output: numeric
  smart_quotes: [apos, apos, quot, quot]
  typographic_symbols:
    ndash: --

mathjax: true
#highlighter: rouge
#highlighter: none
#quiet: false

#pygments: true
lsi:  false # don't produce an index for related posts
safe: false # disables plugins


# Gems
plugins:
  #- jekyll-feed
  #- jekyll-seo-tag
  - jekyll-sitemap
  - jemoji # allow emoji in your post

## Disqus (Set to your disqus id)
#disqus:         jekyll-tale

# Page default value
# defaults:
#   home:
#     heading: "Your awesome heading"
#     subheading: "Your awesome subheading"
#     banner: "Your image url"

#defaults            : []
defaults:
  #- scope:
      #path: '' # an empty string here means all files in the project
      #type: "notes" # a collection in your site, in plural form
    #values:
      #type: "notes" # a collection in your site, in plural form
      #image: "/img/jekyll-og.png"
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      # so as not to add layout to each file
      layout: page
      type: pages
  -
    scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "_notes"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post
  - scope:
      path: "_note"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post
  - scope:
      path: "note"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post

collections:
  note:
    # Default is "/:path/", which is XXX
    #for collections, :collection is part of path
    # It's a must to explicitly set; the global setting cannot override the default
    #permalink: /:collection/:title/
    permalink: /:collection/:title/
    layout: post
    output: true

highlight          : rouge
#include            : ['.htaccess']
include:
  - _pages

# Excludes
#exclude: [ Gemfile, Gemfile.lock ]
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - INSTALL.md
    - README.md
    - .jekyll-cache/
    - .sass-cache/
    - gemfiles/
    - node_modules/
    - vendor/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

#google_site_verification:  ''
#bing_webmastertools_id:    ''
# yandex_site_verification:  ''
# alexa_verify_id:           ''

favicon: "" # the favicon for your site
# Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
# More information » https://mathiasbynens.be/notes/touch-icons
favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'

# Facebook-Optimization › http://j.mp/fb_optimize

og_image:                           'http://ashang.github.io/resp/logo.png'
og_locale:                          'en_EN'
og_type:                            'website'

socialmedia:
    github: ashang

# https://www.google.com/analytics/
# google_analytics: [Tracking ID]
# used in _includes/footer_scripts
# google_analytics_tracking_id:
# Disable when not in production
google_analytics_tracking_id: false

# https://www.tawk.to/knowledgebase/
#
#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts
# tawkto_embed_uri:


# _config_dev.yml is only needed for development.
# start both config-files, overwriting
# the first one with the development variables needed.
# Start dvelopment with › $ jekyll serve --config _config.yml,_config_dev.yml

 # 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

 # <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js"></script>
 # <script>
 # 	WebFont.load({
 # 		google: {
 # 			families: [ 'Lato:400,700,400italic:latin', 'Volkhov::latin' ]
 # 		}
 # 	});
 # </script>

 # <noscript>
 # 	<link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic%7CVolkhov' rel='stylesheet' type='text/css'>
 # </noscript>

algolia_api_key: "0a916ab198bd93d031aa70611271e42e"
