# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Value accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create custom variable and they will be accessible
# in the templates via {{ site.myvariable }}.

email: your-email@example.com
title: in love we trust
subtitle: ramblings notes,
description: >- # this means to ignore newlines until "baseurl:"
 ramblings notes,
 things I worked through to make sure I understand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "http://ashang.github.io/" # the subpath of your site, e.g. /blog
#url: "/" # the base hostname & protocol for your site
#url:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - readme.md
#exclude: ["README.md"]
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

github_username: ashang

# Layout

sidebar: false               # show a sidebar instead of the usual header

#excerpt_separator: "\n\n\n"
show_excerpts: false         # show article excerpts on the home page
#show_excerpts: true

show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar

# always keep the site title visible
show_title: true

# Styling
####
# always keep the header dark
#dark_header: true
#dark_header: false
####

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "README.md", icon: address-card}

#navigation:
#  - {file: "index.html", icon: home}
#  - {file: "README.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

# types available are pages, posts, drafts or any collection
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      # The 'post' type has become 'posts'.
    values:
      layout: "default"

  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "_notes"
      type: "drops" # a collection in your site, in plural form
    values:
      layout: post
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  #- scope:
      #path: ''
    #values:
      #image: "/img/jekyll-og.png"

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
#google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
#cloudinary_url: https://res.cloudinary.com/jekyll/image/upload/f_auto,q_auto,w_404
future: true

navs:
  -
    href: /
    label: HOME

  -
    href: /notes/
    label: TIL

subscribe_rss: /feed.xml

highlighter: rouge
lsi: false
quiet: false
excerpt_separator: "\n\n"

##markdown: kramdown
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
thepro:
  date_format: "%Y%m%d"
date_format: "ordinal"
#date_format: "%B %d, %Y"

permalink: /:title
# pages and collections (excluding posts and drafts) don’t have time
# and categories (for pages, the above :title is equivalent to :basename),
# these aspects of the permalink style are ignored for the output.

lang: "en"

#kramdown:
#  input: GFM
#  syntax_highlighter_opts:
#    default_lang: plaintext
#sass:
#  style: compressed
#strict_front_matter: true

show_excerpts: true

#####name: Aaron Shang
email: Kea Wot <hi@ashang.org>
#####email: hi@ashang.org
## flickr_username: jekyll
## linkedin_username: jekyll

rss: "fee.xml"
#rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# ########

repository: ashang/ashang.github.io

collections:
  posts:
    #permalink: "/:path/"

  note:
    output: true
    permalink: /note/:path/
    # Default is "/:path/"
    #permalink: "/:path/"

