# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n-1)/2   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n-1)   1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
#

def t(n)
  n*(n+1)/2
end

def p(n)
  n*(3*n-1)/2
end

def h(n)
  n*(2*n-1)
end

found = 0
step = 280
while found < 2
  triangle = t(step)
  p_range = (step/1.8).floor
  while (pentagonal = p(p_range)) < triangle
    p_range += 1
  end
  if pentagonal == triangle
    h_range = (step/2.1).floor
    while (hexagonal = h(h_range)) < triangle
      h_range += 1
    end
    if hexagonal == triangle
      puts "Woot! Found #{triangle} at t#{step} p#{p_range} h#{h_range}"
      found += 1
    end
  end
  step += 1
end

#
# Woot! Found 40755 at t285 p165 h143
# Woot! Found 1533776805 at t55385 p31977 h27693
