# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: whiteglass
author: Yous
description: Minimal, responsive Jekyll theme for hackers.
#baseurl: "/whiteglass" # the subpath of your site, e.g. /blog
#url: "https://yous.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
  - CHANGELOG.md
  - jekyll-whiteglass.gemspec
  - screenshot.png
  - vendor

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics:
comments: false

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Defaults
#  enabled: []
#  layout: archive
#  permalinks:
#    year: '/:year/'
#    month: '/:year/:month/'
#    day: '/:year/:month/:day/'
#    tag: '/tag/:name/'
#    category: '/category/:name/'

#defaults            : []
defaults:
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: post
      #layout: page
      # types available are pages, posts, or any collection, in plural form
      type: posts
      # The 'post' type has become 'posts'.
      category: "journal"
      image: "/img/jekyll-og.png"
      #permalink: /:title/
  - scope:
      path: _note
      type: "notes"
    values:
      layout: page
      category: "ramblings"

  -
    scope:
      path: "projects"
      type: "pages" # previously `page`
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Poole"
  - scope:
      path: "img"
    values:
      image: true
  - scope:
      path: "_docs/zh"
    values:
      layout: article
      nav_key: docs
      sidebar:
        nav: docs-zh
      aside:
        toc: true
      lang: zh
      show_edit_on_github: true
      show_date: false
      lightbox: true
  #- scope:
      #path: '' # an empty string here means all files in the project
      #type: "notes" # a collection in your site, in plural form
    #values:
      #type: "notes" # a collection in your site, in plural form
      #image: "/img/jekyll-og.png"
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      # so as not to add layout to each file
      layout: page
      type: pages
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "_note"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post
  - scope:
      path: "note"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post

  #- scope:
      #path: '' # an empty string here means all files in the project
    #values:
      #type: posts
      # The 'post' type has become 'posts'.
      # types available are pages, posts, drafts or any collection, in plural form
      #image: "/img/jekyll-og.png"
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      # so as not to add layout to each file
      layout: page      # Set default layout to page
      type: pages
      show_meta: false	# Hide metadata for all pages
      # sidebar:# Possible values › left, right › by default there will be no sidebar
      comments: false
  - scope:
      path: '' # an empty string here means all files in the project
    values:
      layout: post
      type: posts
  - scope:
      path: "_note"
    values:
      type: "notes" # collection, in plural form
      layout: post
  - scope:
      path: "note"
      type: "notes" # a collection in your site, in plural form
    values:
      layout: post
  -
    scope:
      path: "img"
    values:
      image: true
